### ISSUE TITLE
Filter expression on SyncRule only works when field is used in column filter or properties

### ISSUE THREAD

**Issue by lazyfrosch** [Icinga/icingaweb2-module-director#1130]
The fix in #876 doesn't fix all issues regarding that.

Here is a crude yaml example:

```yaml
rules:
- name: test
  filter_expression: field=*
  properties:
  - source: testdata
    source: ip
    destination: address
```

#876 only fixed that filters on individual properties are taken into account, but the columns used in filter_expression on the rule itself are not taken into account.

/cc @mkayontour @tobiasvdk
