### ISSUE TITLE
Icinga Agent Zone creation Issue 

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-director#1438]
## Expected Behavior
While creating a new Host and initial setting 'Agent' and and 'Accept Config' and 'Accept Commands' to 'yes'.
![screen1](https://user-images.githubusercontent.com/7203835/37777001-d5e5d08e-2de6-11e8-9d1d-18c8fa9215d5.jpg)
During deployment there is in /var/lib/icinga2/api/zones/localhost.localdomain/director/agent_zones.conf  
created with the following content.

cat agent_zones.conf 
object Zone "Dummy1" {
    parent = "localhost.localdomain"
    endpoints = [ "Dummy1" ]
}

After the finished deployment this Object Zone is not available in the Cluster Zone Dropdown Menu of the Host itself or any other Host who wants to add the same 'Cluster Zone'.

![screen2](https://user-images.githubusercontent.com/7203835/37779022-aadc4ee0-2deb-11e8-9ec3-6b3352a52b43.jpg)

Even when disabling the Agent Setting and manually adding the Zone via the Infrastructure Menu.
And then Setting again the Agent Setting to 'Yes' will lead to an object re-defined Zone Error.

## Change/Improvement
Agent-zone.conf should probably list the Zones in the Cluster Zone Drop Down Menu .  

## Current Behavior
agent_zones.conf Zones aren't listed as Members of the Cluster Zone Drop Down Menu.
## Possible Solution
Adding them to the Cluster Zone Dropdown Menu.
 
## Steps to Reproduce (for bugs)
1. Empty Icinga2 Setup with Director and the required Databases.
2. Create 1 Host via Director and Deploy it the the Settings from Screen1.
3. After deployment try to choose from the the Cluster Zone Menu the agent zone which was create during the deployment in  /var/lib/icinga2/api/zones/host/director/agent_zones.conf

Additional:
4. Set Agent Flag on the Host to 'no'.
5. Create Zone via the Infrastructure Menu.
6. Deploy the Zone.
7. Choose the newly added Zone in the Cluster Zone Dropdown Menu and set the Agent Flag again to 'Yes'.

 
## Your Environment
Icinga 2 Version:
icinga2 --version
icinga2 - The Icinga 2 network monitoring daemon (version: r2.8.2-1)

Copyright (c) 2012-2017 Icinga Development Team (https://www.icinga.com/)
License GPLv2+: GNU GPL version 2 or later <http://gnu.org/licenses/gpl2.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Application information:
  Installation root: /usr
  Sysconf directory: /etc
  Run directory: /run
  Local state directory: /var
  Package data directory: /usr/share/icinga2
  State path: /var/lib/icinga2/icinga2.state
  Modified attributes path: /var/lib/icinga2/modified-attributes.conf
  Objects path: /var/cache/icinga2/icinga2.debug
  Vars path: /var/cache/icinga2/icinga2.vars
  PID path: /run/icinga2/icinga2.pid

System information:
  Platform: CentOS Linux
  Platform version: 7 (Core)
  Kernel: Linux
  Kernel version: 3.10.0-693.5.2.el7.x86_64
  Architecture: x86_64

Build information:
  Compiler: GNU 4.8.5
  Build host: unknown

Director Version:
Tested with latest Master 6889c63a693fa3395a5bc7ff028c586f1501db5d  & also with the release 1.4.3

Icingaweb2 Version:
icingaweb2-2.5.1-1.el7.icinga.noarch and the Director Module.

Operating System and version:
cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

* Webserver, PHP versions:
httpd-2.4.6-67.el7.centos.6.x86_64
rh-php71-php-cli.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-common.x86_64       7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-fpm.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-gd.x86_64           7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-intl.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-json.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-ldap.x86_64         7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mbstring.x86_64     7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-mysqlnd.x86_64      7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pdo.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-pgsql.x86_64        7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-xml.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-php-zip.x86_64          7.1.8-1.el7              @centos-sclo-rh       
rh-php71-runtime.x86_64          1-1.el7                  @centos-sclo-rh

**Comment by Punkoivan** [comment]
I am just wondering if this still valid? :) 
I assume that you need to:
1. add zone manually via backend
2. run director kickstart

it should do the trick.

**Comment by C0rn3j** [comment]
Yes, this is still valid as of the latest Feb Director version (1.11.1?).

### Deploy Icinga2 to host via official Ansible role

```yaml
- name: Deploy
  hosts: "TID217"
  roles:
    - install_icinga # Custom role that includes adding repo and stuff
    - icinga.icinga.icinga2
  vars:
    icinga2_confd: false                               # Disable example configuration
    icinga2_purge_features: true                       # Ansible will manage all features
    icinga2_delegate_host: 'master.icinga.fqdn' 
    icinga2_constants:
      NodeName: '{{ inventory_hostname }}'
      ZoneName: '{{ inventory_hostname }}'
    icinga2_features:
      - name: api
        accept_config: true
        ca_host: '123.123.123.123' # 'master.icinga.fqdn'
        ca_host_port: '123'       # '5665' default
        cert_name: '{{ inventory_hostname }}'
        endpoints:
          - name: NodeName
          - name: 'icinga-master'
            host: '123.123.123.123'
            port: '123'
        zones:
          - name: 'master'
            endpoints:
              - 'icinga-master'
          - name: ZoneName
            parent: 'master'
            endpoints:
              - NodeName
          - name: global-templates
            global: true
          - name: director-global
            global: true
      - name: checker
      - name: mainlog
      - name: notification
        state: absent
    icinga_director_user: <username>
    icinga_director_pass: <password>
```

### Add host entry to Director

```yaml
    - name: Create a satellite host in icinga
      delegate_to: localhost
      telekom_mms.icinga_director.icinga_host:
        state: present
        url: 'https://icinga.example/icingaweb2'
        url_username: '{{ icinga_director_user }}'
        url_password: '{{ icinga_director_pass }}'
        address: '{{ icinga_client_ip | default(ansible_default_ipv4.address) | default(ansible_all_ipv4_addresses[0]) }}'
        display_name: '{{ icinga_client_display_name | default(tunel_hostname) | default(inventory_hostname) }}'
        object_name: '{{ icinga_client_fqdn | default(inventory_hostname) }}'
        zone: '{{ icinga_client_fqdn | default(inventory_hostname) }}'
        imports:
          - "Example Satellite"
      vars:
        dnscheck: "no"
```

Which creates the following, as per Preview in Director:

```ini
zones.d/master/hosts.conf
object Host "TID217" {
    import "[Example Satellite](https://icinga.example/icingaweb2/director/host?name=Example%20Satellite)"

    display_name = "sat-host"
    address = "10.123.123.123"
}

zones.d/master/agent_endpoints.conf
object Endpoint "TID217" {
    log_duration = 0s
}

zones.d/master/agent_zones.conf
object Zone "TID217" {
    parent = "master"
    endpoints = [ "TID217" ]
}
```

### Failed director deploy

Now when trying to add the zone in Director instead of Icinga2 + kickstart.

Pre-existing part of Director-added `agent_zones.conf`1, autogenerated from host definition above:

```ini
object Zone "TID217" {
    parent = "master"
    endpoints = [ "TID217" ]
}
```

Director zones.conf I am trying to deploy:
```ini
object Zone "TID217" {
    parent = "master"
}
```


### Workaround

What I can actually do as a workaround is adding the following to `/etc/icinga2/zones.conf` on master Icinga:

```ini
object Endpoint "TID217" {
}
object Zone "TID217" {
        parent = "master"
        endpoints = ["TID217"]
}
```

Then running `icingacli director kickstart run` and deploying in Director.  
Then I can add the host entry, which ends up looking like this in the Director Preview:

```ini
zones.d/master/hosts.conf
object Host "TID217" {
    import "[Example Satellite](https://icinga.example/icingaweb2/director/host?name=Example%20Satellite)"

    display_name = "sat-host"
    address = "10.123.123.123"
}
```

Note I am naming the zone the same as endpoints, which to my understanding, while confusing to some, should be working just fine.
