### ISSUE TITLE
[ Feature Request ] Dictionaries in host objects via Web UI

### ISSUE THREAD

**Issue by MarcusCaepio** [Icinga/icingaweb2-module-director#2722]
Hi all,
I know, we already talked about this in the past and @joni1993 wrote a small patch himself (https://github.com/Icinga/icingaweb2-module-director/issues/2275) but this all did not really work so far for me.
Today I found the Ansible Director Module for the Icinga Director, written bei T-Systems 
https://github.com/T-Systems-MMS/ansible-collection-icinga-director
where I was able to create a host / append a dictionary to a host (which was imported by an import source) via the director API:
```
   - name: Create a host in icinga
      t_systems_mms.icinga_director.icinga_host:
        state: present
        url: "http://xxx/icingaweb2"
        url_username: "xxx"
        url_password: "xxx"
        object_name: "x.x.x"
        append: true
        address: "x.x.x.x"
        groups:
        imports:
          - "linux"
        vars:
          tcp:
            http:
              tcp_port: 80
            https:
              tcp_port: 443
```
what created a wonderful dictionary in my host object
```
object Host "xxx" {
    import "linux"
    display_name = "xxx"
    address = "x.x.x.x"
    vars.tcp = {
        http = {
            tcp_port = 80
        }
        https = {
            tcp_port = 443
        }
   }
}
```
what leads to apply-for rules like
```
apply Service "tcp: " for ( tcp => config in host.vars.tcp ) {
	import "generic-service"
	check_command = "tcp"
	vars += config
	assign where host.vars.tcp
}
```
are working. So theoretically I could
- write my Services, Commands etc. with DSL or configure them in the Director ( I know you prefer using the Director :) ) 
- import Hosts via director's import sources
- adjust these hosts via the ansible module

But it would be nice, if I could do everything at one place. So could we please get dictionaries for host objects via the UI? :)
Thanks a lot and cheers,
Marcus
